#!/usr/bin/env bash
# Generated by preparo v0.1.0
# 15 sample(s) detected
#
# Review parameters before running:
#   --clean-mode strict   (strict | moderate | sensitive)
#   -t 8              (threads)
#
# Activate your conda environment first:
#   conda activate panaroo

set -euo pipefail

mkdir -p panaroo_output

panaroo \
    --clean-mode strict \
    -t 8 \
    -o panaroo_output \
    --remove-invalid-genes \
    bakta_outputs/PA_115_R.gff3 \
    bakta_outputs/PA_141_13.gff3 \
    bakta_outputs/PA_141_2.gff3 \
    bakta_outputs/PA_161_16.gff3 \
    bakta_outputs/PA_16_E_XP.gff3 \
    bakta_outputs/PA_185H_4.gff3 \
    bakta_outputs/PA_263_H_18.gff3 \
    bakta_outputs/PA_280_31.gff3 \
    bakta_outputs/PA_28_DIAG_7.gff3 \
    bakta_outputs/PA_318_31.gff3 \
    bakta_outputs/PA_331_30.gff3 \
    bakta_outputs/PA_50787688.gff3 \
    bakta_outputs/PA_57_9.gff3 \
    bakta_outputs/PA_6987.gff3 \
    bakta_outputs/PA_8_H.gff3

echo 'Panaroo finished. Output in: panaroo_output'

# Expected outputs for bioentro-suite:
#   panaroo_output/gene_presence_absence.csv  ← pangenome matrix
#   panaroo_output/pan_genome_reference.fa     ← representative sequences
#   panaroo_output/core_gene_alignment.aln      ← core genome alignment
